### ISSUE TITLE
Easing animations not working in ARM-64 bit devices.

### ISSUE THREAD

**Issue by ghost** [zrxq/UIView-EasingFunctions#11]
I am trying the code below , it works fine in iPhone 5 , iPhone 4 but doesn't work properly in iPhone 5S. 

```
 [viewButtonContainer setEasingFunction:QuadraticEaseIn forKeyPath:@"center"]; 

[UIView animateWithDuration:0.3 delay:waitFor options:UIViewAnimationOptionCurveLinear animations:^{
viewButtonContainer.center = CGPointMake(0,0);

} completion:^(BOOL finished) {

}];
```

Something to compile for ARM-64 may be ?

**Comment by ghost** [comment]
My bad, didn't see the closed issues. Commenting for the first time on Github, please understand

**Comment by zrxq** [comment]
It's my fault, actually, shouldn't have closed the issue in the first place. Thanks for reporting, I'm going to look into it.
