### ISSUE TITLE
Wrong animation when using 

### ISSUE THREAD

**Issue by iamBlueGene** [zrxq/UIView-EasingFunctions#14]
When I use EasingFunctions with CABasicAnimation I get the wrong behavior when adding an easing function. 
Example code:

[self.button setEasingFunction:CubicEaseOut forKeyPath:@"transform.scale"];
    CATransform3D trans = [(CALayer *)[self.button.layer presentationLayer] transform];
    CABasicAnimation *animation = nil;
    animation = [CABasicAnimation animationWithKeyPath:@"transform.scale"];
    [animation setFromValue:[NSNumber numberWithDouble:1.0f]];
    [animation setDuration:1.0f];
    animation.fillMode = kCAFillModeForwards;
    self.button.layer.transform = CATransform3DMakeScale(1.25, 1.25, 1.25);
    [self.button.layer addAnimation:animation forKey:@"transform.scale"];

Explanation:
I'm animating a button to scale from 1 to 1.25 and instead of growing it firsts shrinks until you can't see it and then when the animation time passes it is becoming 1.25

**Comment by zrxq** [comment]
This has nothing to do with UIView+EasingFunctions. The category is designed to be used with `[UIView animateWithDuration...]` methods, please consider using [AHEasing](https://github.com/warrenm/AHEasing) category on `CAAnimation` instead.
