### ISSUE TITLE
Easing with constraints

### ISSUE THREAD

**Issue by brennanMKE** [zrxq/UIView-EasingFunctions#3]
I am using autolayout and and constraints more and more. One use is to set the constant of leading space of a content view to push the view left or right while there is a width constraint and no trailing constraint. It is how I am creating a sidebar interface.

I see that this project can manipulate some values but I do not see how I would modify this code to work with modifying a constant on a constraint. How would you do this sort of animation to allow for easing?

**Comment by zrxq** [comment]
Autolayout engine operates on `UIView` properties (`center` and `bounds`), so you just need to attach an easing function to one of those.

To animate a constraint change, update the constraint programmatically, then send `layoutIfNeeded` message to the view from within an animation block. There are many questions and answers on the subject on [stackoverflow](http://stackoverflow.com).
