### ISSUE TITLE
CocoaPods integration

### ISSUE THREAD

**Issue by kaandedeoglu** [zrxq/UIView-EasingFunctions#4]
Not really an issue, but I would love to be able to add this project remotely with CocoaPods, rather than adding it locally via a podspec.

**Comment by matej** [comment]
Agree. It would be nice to have this added to https://github.com/CocoaPods/Specs

**Comment by zrxq** [comment]
Now available as 'UIView+EasingFunctions', '~> 0.0.1'

http://cocoapods.org/?q=uiview%2Beasingfunctions
