### ISSUE TITLE
CocoaPod should depend on AHEasing?

### ISSUE THREAD

**Issue by orta** [zrxq/UIView-EasingFunctions#6]
Hey there @zrxq I was wondering your opinion on making the podspec for this library depend on AHEasing, as at the minute in order to use this library you have to specify separately AHEasing in the podfile.

**Comment by zrxq** [comment]
Sounds reasonable and originally I intended to do exactly this. However, in fact, the library can be used perfectly fine without AHEasing, the latter just makes it easier to use the library straight out of the box, without having to define easing functions yourself. Let's say using AHEasing is recommended, but totally optional. And it felt a bit cleaner to let the users decide whether they want AHEasing included in their projects than enforcing them to mess with the lib's podspec in case they don't.

Anyway, this is not something I'm fully convinced about and I'd appreciate your thoughts.

**Comment by orta** [comment]
Well, the flow I used to find your library was `pod search uiview` which gave

```
-> UIView+EasingFunctions (0.0.1)
   A category on UIView that allows to use custom easing functions with block-based animations.
   - Homepage: https://github.com/zrxq/UIView-EasingFunctions
   - Source:   https://github.com/zrxq/UIView-EasingFunctions.git
   - Versions: 0.0.1 [master repo]
```

So after installing and thinking _I'll read the header and figure it out_ I couldn't find any references to the `ViewEasingFunctionPointerType` in the code base and went back to the README where I found the reference to `AHEasing`.

Here's how that could be improved IMO:
- Use Appledoc comments in the header ( you should do this anyway ;) see [CocoaDocs](http://cocoadocs.org/docsets/UIView+EasingFunctions/0.0.1/Categories/UIView+Easing.html) ) which says that you can use your own but there are a bunch of great pre-made ones on AHEasing
- Set the pod dependency, which covers the 90% use case
- Or change the podspec description to mention that you can include AHEasing for defaults

**Comment by zrxq** [comment]
> So after installing and thinking I'll read the header and figure it out I couldn't find any references to the ViewEasingFunctionPointerType in the code base and went back to the README where I found the reference to AHEasing.

Ow, that's embarrassing. I'll do something about it. Thanks for the input!

**Comment by zrxq** [comment]
Added appledoc comments to the header, hope now it makes more sense.

**Comment by orta** [comment]
:+1:
