### ISSUE TITLE
Problem animating origin and size of a frame.

### ISSUE THREAD

**Issue by thelbane** [zrxq/UIView-EasingFunctions#8]
If I use, for example, an ExponentialEaseInOut on a UIView that is 100 points tall and aligned to the bottom of its parent view to animate its origin and size to make it appear to grow bottom-aligned to 200 points, the bottom "detaches" from the bottom of the superview. Expected behavior is that the same easing math applies to both the origin and size, so the bottom appears to remain fixed.

```
[view setEasingFunction:ExponentialEaseInOut forKeyPath:@"frame"];
[UIView animateWithDuration:0.5
                      delay:0
                    options:0
                 animations:^{
                     view.frame = CGRectMake(0,view.superview.frame.size.height - 200,view.frame.size.width,200); // animates to correct new position and size, but the bottom doesn't stay "fixed" to the bottom of the superview
                 }
                 completion:nil];
```

**Comment by thelbane** [comment]
I just want to add that I love how easy this library is to use. :)

**Comment by zrxq** [comment]
Hi, I was unable to reproduce the issue. Could you please check this repo: https://github.com/zrxq/EasingFrameProblem and compare the code with yours? 

P.S. Really glad to hear the library is easy to use, thanks!

**Comment by thelbane** [comment]
Hi Zoreslav,

Wow! Thank you for building out the test project. You built out the
scenario correctly and it does not reproduce the issue. I'm going to dig
into my code base and see what differences there are.

Thank you!
-Lee

On Fri, Nov 22, 2013 at 10:50 PM, Zoreslav Khimich <notifications@github.com

**Comment by zrxq** [comment]
Hi Lee,

You're welcome!

Any news on this one? Could you provide me with a way to reproduce the original issue? 

Cheers,
Zoreslav.
